import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateEnvFile } from "@/domains/config/config-generator.js";
import { pathExists } from "fs-extra";

// Note: Full integration tests for runSetupWizard require mocking @clack/prompts
// These tests cover unit functionality and file operations

describe("setup-wizard", () => {
	let tempDir: string;
	let globalDir: string;

	beforeEach(async () => {
		tempDir = join(tmpdir(), `ck-test-${Date.now()}`);
		globalDir = join(tmpdir(), `ck-global-${Date.now()}`);
		await mkdir(tempDir, { recursive: true });
		await mkdir(globalDir, { recursive: true });
	});

	afterEach(async () => {
		await rm(tempDir, { recursive: true, force: true });
		await rm(globalDir, { recursive: true, force: true });
	});

	test("should skip wizard when .env exists", async () => {
		await writeFile(join(tempDir, ".env"), "EXISTING=value");
		const envExists = await pathExists(join(tempDir, ".env"));
		expect(envExists).toBe(true);
	});

	test("should detect global .env for inheritance", async () => {
		await writeFile(join(globalDir, ".env"), "GEMINI_API_KEY=global-key");
		const envExists = await pathExists(join(globalDir, ".env"));
		expect(envExists).toBe(true);
	});

	describe("generateEnvFile", () => {
		test("should create .env file with provided values", async () => {
			const values = {
				GEMINI_API_KEY: "test-key-123",
				DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/test",
			};
			await generateEnvFile(tempDir, values);

			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("GEMINI_API_KEY=test-key-123");
			expect(content).toContain("DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/test");
		});

		test("should preserve alternative provider keys and image provider selection", async () => {
			const values = {
				OPENROUTER_API_KEY: "sk-or-v1-abcdefghijklmnopqrstuvwxyz123456",
				MINIMAX_API_KEY: "minimax_test_key_1234567890",
				IMAGE_GEN_PROVIDER: "openrouter",
			};
			await generateEnvFile(tempDir, values);

			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("OPENROUTER_API_KEY=sk-or-v1-abcdefghijklmnopqrstuvwxyz123456");
			expect(content).toContain("MINIMAX_API_KEY=minimax_test_key_1234567890");
			expect(content).toContain("IMAGE_GEN_PROVIDER=openrouter");
		});

		test("should skip empty values", async () => {
			const values = {
				GEMINI_API_KEY: "test-key",
				EMPTY_VALUE: "",
			};
			await generateEnvFile(tempDir, values);

			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("GEMINI_API_KEY=test-key");
			expect(content).not.toContain("EMPTY_VALUE");
		});

		// Skip on Windows - Unix file permissions not supported
		test.skipIf(process.platform === "win32")(
			"should set restrictive file permissions (0600)",
			async () => {
				await generateEnvFile(tempDir, { KEY: "value" });
				const envPath = join(tempDir, ".env");
				const stats = await stat(envPath);
				// Check owner-only read/write (0600 = 384 in decimal)
				const mode = stats.mode & 0o777;
				expect(mode).toBe(0o600);
			},
		);

		test("should include header comments", async () => {
			await generateEnvFile(tempDir, { KEY: "value" });
			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("# Generated by ClaudeKit CLI");
		});
	});

	describe(".env parsing edge cases", () => {
		test("should handle quoted values", async () => {
			await writeFile(join(tempDir, ".env"), "KEY=\"quoted value\"\nKEY2='single quoted'");
			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain('"quoted value"');
			expect(content).toContain("'single quoted'");
		});

		test("should handle export prefix", async () => {
			await writeFile(join(tempDir, ".env"), "export KEY=value\nNORMAL=val");
			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("export KEY=value");
		});

		test("should handle values with equals signs", async () => {
			await writeFile(join(tempDir, ".env"), "URL=https://example.com?foo=bar&baz=qux");
			const content = await readFile(join(tempDir, ".env"), "utf-8");
			expect(content).toContain("foo=bar");
		});

		test("should skip comment lines", async () => {
			const envContent = "# This is a comment\nKEY=value\n# Another comment";
			await writeFile(join(tempDir, ".env"), envContent);
			const exists = await pathExists(join(tempDir, ".env"));
			expect(exists).toBe(true);
		});
	});
});
