import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { CodexCapabilities } from "../codex-capabilities.js";
import { CODEX_CAPABILITY_TABLE } from "../codex-capabilities.js";
import { buildWrapperScript, generateCodexHookWrappers } from "../codex-hook-wrapper.js";

const testDir = join(tmpdir(), "ck-codex-hook-wrapper-test");
const caps: CodexCapabilities = CODEX_CAPABILITY_TABLE[0];

beforeAll(() => {
	mkdirSync(testDir, { recursive: true });
});

afterAll(() => {
	rmSync(testDir, { recursive: true, force: true });
});

describe("buildWrapperScript", () => {
	it("includes the original hook path in the script", () => {
		const script = buildWrapperScript("/home/user/.claude/hooks/session-init.cjs", caps);
		expect(script).toContain("/home/user/.claude/hooks/session-init.cjs");
	});

	it("generates a valid CommonJS shebang", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script.startsWith("#!/usr/bin/env node")).toBe(true);
	});

	it("contains the AUTO-GENERATED marker", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("AUTO-GENERATED by claudekit");
	});

	it("encodes strip rules for PreToolUse (additionalContext)", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// PreToolUse does not support additionalContext → must be in STRIP_RULES
		expect(script).toContain("PreToolUse");
		expect(script).toContain("additionalContext");
	});

	it("does not strip additionalContext for PostToolUse (it is supported)", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// PostToolUse supports additionalContext so should NOT be in STRIP_RULES
		// The STRIP_RULES object only contains events where fields need stripping
		const scrubRulesMatch = script.match(/const SCRUB_RULES = (\{.*?\});/s);
		if (scrubRulesMatch === null) {
			throw new Error("SCRUB_RULES declaration not found in generated script");
		}
		const scrubRules = JSON.parse(scrubRulesMatch[1]);
		// PostToolUse should not be in scrub rules (it supports additionalContext)
		expect(scrubRules.PostToolUse).toBeUndefined();
	});

	it("uses spawnSync to invoke the original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("spawnSync");
	});

	it("reads stdin and passes it to original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("process.stdin");
	});

	it("forwards stderr from original hook", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("process.stderr.write");
	});

	it("parses stdout as JSON and sanitizes it", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("JSON.parse");
		expect(script).toContain("JSON.stringify");
	});

	it("passes through non-JSON output unchanged", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// Non-JSON handling lives in the catch block after JSON.parse.
		expect(script).toContain("Non-JSON stdout");
	});
});

describe("buildWrapperScript — M4 timeout", () => {
	it("M4 — embeds default 30000ms timeout when no hookTimeoutMs provided", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		expect(script).toContain("HOOK_TIMEOUT_MS = 30000");
	});

	it("M4 — embeds custom timeout when hookTimeoutMs provided", () => {
		const script = buildWrapperScript("/hook.cjs", caps, 60000);
		expect(script).toContain("HOOK_TIMEOUT_MS = 60000");
		expect(script).not.toContain("HOOK_TIMEOUT_MS = 30000");
	});

	it("M4 — wrapper uses HOOK_TIMEOUT_MS in spawnSync call", () => {
		const script = buildWrapperScript("/hook.cjs", caps, 45000);
		// Should reference HOOK_TIMEOUT_MS (not hardcoded 30000) in spawnSync options
		expect(script).toContain("timeout: HOOK_TIMEOUT_MS");
	});
});

describe("buildWrapperScript — M5 signal exit", () => {
	it("M5 — uses ?? 1 (not || 0) for exit code fallback", () => {
		const script = buildWrapperScript("/hook.cjs", caps);
		// Should use nullish coalescing fallback of 1, not short-circuit or 0
		expect(script).toContain("result.status ?? 1");
		expect(script).not.toContain("result.status || 0");
	});
});

describe("generateCodexHookWrappers", () => {
	it("generates wrapper files in target directory", () => {
		const wrapperDir = join(testDir, "wrapper-output");
		const originals = [join(testDir, "session-init.cjs"), join(testDir, "privacy-block.cjs")];

		const results = generateCodexHookWrappers(originals, wrapperDir, caps);

		expect(results).toHaveLength(2);
		for (const r of results) {
			expect(r.success).toBe(true);
			expect(existsSync(r.wrapperPath)).toBe(true);
		}
	});

	it("wrapper file preserves original filename", () => {
		const wrapperDir = join(testDir, "wrapper-names");
		const results = generateCodexHookWrappers(
			["/home/user/.claude/hooks/my-hook.cjs"],
			wrapperDir,
			caps,
		);
		expect(results[0].wrapperPath).toContain("my-hook.cjs");
	});

	it("creates wrapper directory if it does not exist", () => {
		const wrapperDir = join(testDir, "new-wrapper-dir");
		expect(existsSync(wrapperDir)).toBe(false);

		generateCodexHookWrappers(["/original.cjs"], wrapperDir, caps);
		expect(existsSync(wrapperDir)).toBe(true);
	});

	it("returns empty array for empty input", () => {
		const results = generateCodexHookWrappers([], join(testDir, "empty"), caps);
		expect(results).toHaveLength(0);
	});

	it("wrapper content contains reference to original path", () => {
		const wrapperDir = join(testDir, "wrapper-content");
		const originalPath = "/home/user/.claude/hooks/session-init.cjs";

		const results = generateCodexHookWrappers([originalPath], wrapperDir, caps);
		expect(results[0].success).toBe(true);

		const content = readFileSync(results[0].wrapperPath, "utf8");
		expect(content).toContain(originalPath);
	});
});

/**
 * Behavioral tests for the Claude-Code-exit-code → Codex-JSON translation (#738).
 * Each test generates a real wrapper script around a synthetic original hook,
 * invokes the wrapper via `node`, and asserts stdout/exit-code.
 */
describe("buildWrapperScript — exit-code → JSON protocol translation (#738)", () => {
	function writeFakeOriginalHook(
		path: string,
		body: { exit: number; stdout?: string; stderr?: string },
	): void {
		const stdoutLit = body.stdout ? JSON.stringify(body.stdout) : '""';
		const stderrLit = body.stderr ? JSON.stringify(body.stderr) : '""';
		writeFileSync(
			path,
			`#!/usr/bin/env node
if (${stdoutLit}) process.stdout.write(${stdoutLit});
if (${stderrLit}) process.stderr.write(${stderrLit});
process.exit(${body.exit});
`,
			{ mode: 0o755 },
		);
	}

	function runWrapper(
		wrapperPath: string,
		event: string,
	): { stdout: string; stderr: string; status: number | null } {
		const result = spawnSync(process.execPath, [wrapperPath], {
			input: JSON.stringify({ hook_event_name: event }),
			encoding: "utf8",
		});
		return { stdout: result.stdout, stderr: result.stderr, status: result.status };
	}

	it("exit 2 + stderr + no stdout on PreToolUse → emits permissionDecision:deny + exit 0", () => {
		const wrapperDir = join(testDir, "trans-exit2-nostdout");
		const originalHook = join(testDir, "block-hook.cjs");
		writeFakeOriginalHook(originalHook, { exit: 2, stderr: "Path is blocked" });

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		expect(results[0].success).toBe(true);

		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		expect(out.status).toBe(0);
		const parsed = JSON.parse(out.stdout);
		expect(parsed.permissionDecision).toBe("deny");
		expect(parsed.reason).toBe("Path is blocked");
	});

	it("exit 2 + non-JSON stdout on PreToolUse → uses stdout as deny reason", () => {
		const wrapperDir = join(testDir, "trans-exit2-rawstdout");
		const originalHook = join(testDir, "raw-block.cjs");
		writeFakeOriginalHook(originalHook, { exit: 2, stdout: "Denied: env access" });

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		expect(out.status).toBe(0);
		const parsed = JSON.parse(out.stdout);
		expect(parsed.permissionDecision).toBe("deny");
		expect(parsed.reason).toBe("Denied: env access");
	});

	it("exit 2 on Stop (no deny support) → exit code passes through without translation", () => {
		const wrapperDir = join(testDir, "trans-stop-event");
		const originalHook = join(testDir, "stop-block.cjs");
		writeFakeOriginalHook(originalHook, { exit: 2, stderr: "Stop blocked" });

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "Stop");
		expect(out.status).toBe(2);
		expect(out.stdout).toBe("");
		expect(out.stderr).toContain("Stop blocked");
	});

	it("exit 0 + no stdout → silent allow, no translation", () => {
		const wrapperDir = join(testDir, "trans-silent-allow");
		const originalHook = join(testDir, "allow-hook.cjs");
		writeFakeOriginalHook(originalHook, { exit: 0 });

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		expect(out.status).toBe(0);
		expect(out.stdout).toBe("");
	});

	it("hook emits valid JSON with deny → scrubbed and passed through, exit 0", () => {
		const wrapperDir = join(testDir, "trans-json-deny");
		const originalHook = join(testDir, "json-deny.cjs");
		writeFakeOriginalHook(originalHook, {
			exit: 0,
			stdout: JSON.stringify({
				permissionDecision: "deny",
				reason: "Blocked by rule",
				additionalContext: "should-be-scrubbed",
			}),
		});

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		expect(out.status).toBe(0);
		const parsed = JSON.parse(out.stdout);
		expect(parsed.permissionDecision).toBe("deny");
		expect(parsed.reason).toBe("Blocked by rule");
		// additionalContext scrubbed for PreToolUse
		expect(parsed.additionalContext).toBeUndefined();
	});

	it("exit 2 + JSON with permissionDecision:deny → keeps hook's reason, exits 0 (consistency)", () => {
		const wrapperDir = join(testDir, "trans-exit2-json-hasDeny");
		const originalHook = join(testDir, "json-deny-exit2.cjs");
		writeFakeOriginalHook(originalHook, {
			exit: 2,
			stdout: JSON.stringify({
				permissionDecision: "deny",
				reason: "Hook-supplied reason",
			}),
		});

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		// Translating: exit 0 keeps the deny authoritative (same contract as emitDeny)
		expect(out.status).toBe(0);
		const parsed = JSON.parse(out.stdout);
		expect(parsed.permissionDecision).toBe("deny");
		// Hook's own reason preserved — not overwritten by the translator
		expect(parsed.reason).toBe("Hook-supplied reason");
	});

	it("exit 2 + JSON without permissionDecision → translates to deny", () => {
		const wrapperDir = join(testDir, "trans-exit2-json-noDeny");
		const originalHook = join(testDir, "json-bare.cjs");
		writeFakeOriginalHook(originalHook, {
			exit: 2,
			stdout: JSON.stringify({ something: "else" }),
			stderr: "Nope",
		});

		const results = generateCodexHookWrappers([originalHook], wrapperDir, caps);
		const out = runWrapper(results[0].wrapperPath, "PreToolUse");
		expect(out.status).toBe(0);
		const parsed = JSON.parse(out.stdout);
		expect(parsed.permissionDecision).toBe("deny");
		expect(parsed.reason).toBe("Nope");
	});
});
